# bash
L$ %h/.config/bash - - - - @dotfiles@/.config/bash
L$ %h/.config/shell - - - - @dotfiles@/.config/shell
L$ %h/.inputrc - - - - @dotfiles@/.inputrc
L$ %h/.bashrc - - - - @dotfiles@/.bashrc
L$ %h/.profile - - - - @dotfiles@/.profile
