# bash
L$ %h/.zshrc - - - - @dotfiles@/.zshrc
L$ %h/.profile - - - - @dotfiles@/.profile
L$ %h/.config/zsh - - - - @dotfiles@/.config/zsh
L$ %h/.config/shell - - - - @dotfiles@/.config/shell
L$ %h/.profile - - - - @dotfiles@/.profile
L$ %h/.zprofile - - - - %h/.profile

# delete files that prevent loading of .zprofile
r %h/.zshenv - - - - -
r %h/.zlogin - - - - -
