#!/usr/bin/env bash

set -euo pipefail

# TODO differentiate between powered: no and no adapters
# TODO bluetoothctl may hang if there are no bluetooth adapters?
print_state() {
    # bluetoothctl hangs if there are no adapters and --timeout can be minimum
    # of one second and that is very slow
    if [[ -z "$(timeout 0.3s bluetoothctl list)" ]]; then
        printf '{"status":"unknown"}'
        return
    fi

    pat='.*Powered: *([a-zA-Z]+).*'
    local powered="unknown"
    if [[ "$(bluetoothctl show)" =~ $pat ]]; then
        powered="${BASH_REMATCH[1]}"
    fi

    local connected="false"
    if bluetoothctl devices Connected &>/dev/null; then
        connected="true"
    fi

    printf '{"status":"%s","connected":%s}\n' "$powered" "$connected"
}

print_state

bluetoothctl --monitor | while read -r _; do
    print_state
done
