#!/usr/bin/env bash

set -euo pipefail

WM_EXEC="${WM_EXEC:-echo}"

case "${1:-}" in
    left)
        "$WM_EXEC" pavucontrol
        ;;
    right)
        # TODO path?
        # scripts/sink-switcher.py &>/dev/null
        ;;
    middle)
        wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle &>/dev/null
        ;;
    up)
        wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 2%+ &>/dev/null
        ;;
    down)
        wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%- &>/dev/null
        ;;
    monitor)
        inspect() {
            local volume="$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{ print "{\"volume\":" int($2 * 100) ",\"muted\":" ($3 == "[MUTED]" ? "true" : "false" ) }')"

            bluetooth="false"
            if [[ "$(wpctl inspect @DEFAULT_AUDIO_SINK@)" =~ .*bluez.* ]]; then
                bluetooth="true"
            fi

            echo "$volume,\"is_bluetooth\":$bluetooth}"
        }

        inspect

        # update when anything changes
        pactl subscribe | grep --line-buffered "change" | while read -r _; do
            inspect
        done
        ;;
esac

