# turn off monitors after 5min (TODO asus monitor is a pain)
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# suspend after 10min
listener {
    timeout = 600
    on-timeout = systemctl suspend
    # on-resume = hyprctl dispatch dpms on
}
