source = monitor.conf

$mon1 = HDMI-A-1
$mon2 = DVI-D-1

$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun -show-icons

$bar = ~/.config/waybar/waybar.sh

exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME
exec-once = /usr/lib/pam_kwallet_init &
exec-once = $bar &
exec-once = mako &

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

source = theming.conf

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

source = input.conf

source = keybindings.conf

windowrulev2 = bordercolor rgb(FF0000) rgb(880808),fullscreen:1

windowrule = float, initialTitle:overskride
windowrule = float, class:org.pulseaudio.pavucontrol

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
