#!/usr/bin/env python3

import subprocess
import re
import time
import os

from typing import List, Tuple, Optional

def get_devices() -> List[Tuple[str, str]]:
    result = subprocess.run(
        ["bluetoothctl", "devices", "Connected"],
        capture_output=True
    )
    result.check_returncode()

    devices = []

    for line in result.stdout.decode("utf-8").splitlines():
        # extract name and address from 'Device XX:XX:XX:XX:XX:XX NAME'
        re_results = re.search(r"([A-F0-9]{2}:[A-F0-9]{2}:[A-F0-9]{2}:[A-F0-9]{2}:[A-F0-9]{2}:[A-F0-9]{2}) (.*)$", line, re.IGNORECASE)
        if not re_results:
            continue

        devices.append((re_results.group(1), re_results.group(2)))

    return devices

def get_device_rssi(device: str) -> Optional[int]:
    result = subprocess.run(["hcitool", "rssi", device], capture_output=True)
    result.check_returncode()

    # extract value from 'RSSI return value: -21'
    re_results = re.search(r"(-?\d+)", result.stdout.decode("utf-8"))
    if not re_results:
        return None

    return int(re_results.group(1))

def main():
    """
    Simple script that shows RSSI of connected bluetooth devices

    Useful for debugging signal issues
    """
    cmd = subprocess.run(["clear"], capture_output=True)
    clear = cmd.stdout.decode("utf-8")

    try:
        while True:
            print(f"{clear}Listing bluetooth RSSI of connected devices:")
            for d_addr, d_name in get_devices():
                print(f"  {d_name} {d_addr} = {get_device_rssi(d_addr)}")

            time.sleep(0.5)
    except KeyboardInterrupt:
        pass

if __name__ == "__main__":
    main()

