#!/usr/bin/env bash
# simple wrapper around nix develop that makes gc roots for each shell

set -eo pipefail

TARGET_DEFAULT="default"
TARGET_PREFIX=".#devShells.x86_64-linux"



function name_gen() {
    # im using sha256 cause base64 creates huge strings and i dont need to
    # reverse the process, it still means it will be the same if the input is
    # the same
    echo -n "${1:?}" | sha256sum | head -c 16
}



function nix_flake_inputs() {
    # TODO idk if the last path of the source should be preserved?
    nix flake archive --dry-run --json | grep -Po '"path":"\K[^"]*' | head -n -1
}

cmd="$1"
shift || true

case "$cmd" in
    '') # default just start the default shell
        TARGET="${TARGET_PREFIX}.${TARGET_DEFAULT}"
        ;;
    .#*) # pass the flake specifier
        TARGET="$cmd"
        ;;
    *) # use the argument as devShells name
        TARGET="${TARGET_PREFIX}.$cmd"
        ;;
esac

link_dir="$LINK_DIR/$(name_gen "${TARGET:?}")"

nix_inputs=($(nix_flake_inputs))

# link for this particular target

# rebuild if requested or if the derivation is missing (invalid or missing link)

# create indirect root for each input
i=0
for input in "${nix_inputs[@]}"; do
    # create root for each input
    nix-store --add-root "$link_dir/$i" --indirect --realise "$input" &>/dev/null
    i=$(( i + 1 ))
done

# build the devshell input derivation which creates a gc root
nix build -o "$link_dir/devshell" "$TARGET.inputDerivation"

exec nix develop "$TARGET" --offline --command "$SHELL"
