#!/usr/bin/env bash
# simple wrapper script to run command under firejail
#
# this script exists because
# https://github.com/netblue30/firejail/issues/5713

set -eo pipefail

# TODO set env var for npm or smth cause theres no execution rights in ~/.npm
args=(
    --quiet

    # keep tab completions
    --tab
    --keep-shell-rc

    --blacklist=/mnt
    --blacklist=/media

    # disable default profile
    --noprofile

    # mount tmpfs on ~/.cache
    --private-cache
    --private-dev

    # die when first child dies
    --deterministic-shutdown
)

# whitelisted RW paths
whitelist=(
  "$PWD"
)

# whitelisted RO paths
whitelist_ro=(
    # my scripts
    "$HOME/.bin"

    "$HOME/.inputrc" # needed for bash
    "$HOME/.bashrc"
    "$HOME/.zshrc"
    "$HOME/.zcompdump"

    # configs (explicit cause they are often symlinks)
    "$HOME/.config/shell" # shell agnostic files
    "$HOME/.config/zsh"
    "$HOME/.config/bash"
    "$HOME/.config/nano"
    "$HOME/.config/helix"
    "$HOME/.config/nvim"
    "$HOME/.config/emacs"
    "$HOME/.config/zellij"
    "$HOME/.config/tmux"
    "$HOME/.config/git"

    # allow nix config (to allow running flake shells)
    "$HOME/nix-config"
)

POSITIONAL_ARGS=()
while [ $# -gt 0 ]; do
    case $1 in
        --rw)
            whitelist+=("$2")
            shift 2
            ;;
        --ro)
            whitelist_ro+=("$2")
            shift 2
            ;;
        --)
            # save rest as args
            POSITIONAL_ARGS+=("$@")
            break
            ;;
        -*)
            args+=("$1")
            shift
            ;;
        *)
            # save positional arg
            POSITIONAL_ARGS+=("$1")
            shift
            ;;
    esac
done

# restore positional parameters
set -- "${POSITIONAL_ARGS[@]}"

for path in "${whitelist[@]}"; do
    args+=("--whitelist=$path")
done

for path in "${whitelist_ro[@]}"; do
    args+=(
        "--whitelist=$path"
        "--read-only=$path"
    )
done

if [[ -z "$*" ]]; then
    echo "Usage: $0 <command...>"
    exit 1
fi

if [[ "$PWD" == "/home/$USER" ]]; then
    echo "Running in HOME directory is unsafe"
    exit 66
fi

exec firejail "${args[@]}" -- "$@"
