#!/usr/bin/env bash
# experimental version of network-probe which does the pinging in parallel

IPS=(192.168.1.1 1.1.1.1 8.8.8.8)

while IFS= read -r line; do
    if [[ "$line" =~ \[([0-9]+\.[0-9]+)\].+\ from\ ([0-9\.]+):.+\ time=([0-9\.]+)\ ms.* ]]; then
        echo "${BASH_REMATCH[1]},${BASH_REMATCH[2]},${BASH_REMATCH[3]}"
    elif [[ "$line" =~ \[([0-9]+\.[0-9]+)\].+\ from\ ([0-9\.]+):.+ ]]; then
        # destination unreachable
        echo "${BASH_REMATCH[1]},${BASH_REMATCH[2]},4000"
    fi
done < <(
    for i in "${IPS[@]}"; do
        ping -W 2 -D "$i" -i 4 &
    done
)

