#!/usr/bin/env bash
# probes multiple IPs and outputs JSON object per line for analysis
#
# this script has only single dependency: ping

set -eo pipefail

IPS=(192.168.1.1 1.1.1.1 8.8.8.8)
PING_TIMEOUT=2 # seconds
PING_TIMEOUT_MS="$(( PING_TIMEOUT * 1000 ))"

output_dir="${1:?No output directory provided}"

# make sure output exists
mkdir -p "$output_dir" || true
if [[ ! -d "$output_dir" ]]; then
    echo "Output path '${output_dir}' is not a directory"
    exit 1
fi

gen_filename() {
    printf "$output_dir/%(%Y-%m-%d)T.log" -1
}
output_file="$(gen_filename)"
echo "Output file: $output_file"

log() {
    # reset seconds counter
    SECONDS=0

    # print single timestamp (avoid external commands)
    printf "{ \"timestamp\": \"%(%Y-%m-%dT%H:%M:%S%z)T\"" -1
    for i in "${IPS[@]}"; do
        {
            line=$(ping -D -W "$PING_TIMEOUT" -c 1 "${i:?}") || true

            # NOTE time is not measured if the target is unreachable or timeout is reached
            latency="$PING_TIMEOUT_MS"
            if [[ "$line" =~ .+\ time=([0-9\.]+)\ ms.* ]]; then
                latency="${BASH_REMATCH[1]}"
            fi

            # print in json format
            echo -n ", \"$i\": $latency"
        } &
    done

    # wait for all pings
    wait

    # finish the json object and start newline
    echo " }"

    # sleep if the ping was fast
    elapsed=$SECONDS
    if (( $elapsed < $PING_TIMEOUT )); then
        sleep $(( $PING_TIMEOUT - $elapsed ))
    fi
}

while :; do
    # swap files at midnight
    printf -v timestamp "%(%H:%M)T" -1
    if [[ "$timestamp" == "00:00" ]]; then
        file="$(gen_filename)"
        if [[ "$(gen_filename)" != "$output_file" ]]; then
            output_file="$file"
            echo "Output file: $output_file"
        fi
    fi

    line="$(log)"
    echo "$line"
    echo "$line" >> "$output_file"
done
