#!/usr/bin/env bash
# basic wayout widget timer

set -euo pipefail

LOCKFILE="/tmp/.timer-wayout"

wayout_cmd=""
if command -v wayout &>/dev/null; then
    wayout_cmd="wayout"
elif command -v proycon-wayout &>/dev/null; then # nixos
    wayout_cmd="proycon-wayout"
else
    echo "wayout not found in PATH!"
    exit 1
fi

# if already running kill the running instance and quit
exec 200<>"$LOCKFILE"
if ! flock -n 200; then
    read pid <&200
    echo "Process $pid already running, terminating it.."

    # send INT signal then KILL
    kill -INT "-$pid" &>/dev/null || true
    sleep 1s
    kill -KILL "-$pid" &>/dev/null || true

    exit 0
fi
echo "$$" >&"200" # write PID

# reset seconds counter
SECONDS=0

function display() {
    # print human readable time
    T="$SECONDS"
    D=$((T/60/60/24))
    H=$((T/60/60%24))
    M=$((T/60%60))
    S=$((T))
    rel_time=""
    (( D > 0 )) && rel_time="$rel_time${D}d "
    (( H > 0 )) && rel_time="$rel_time${H}h "
    (( M > 0 )) && rel_time="$rel_time${M}m "

    # show minute when its less than a minute
    if [[ -z "$rel_time" ]]; then
        rel_time="1m "
    fi

    # remove any leftover spaces
    rel_time="${rel_time% }"

    color=""
    if (( T >= (60 * 60) )); then
        color="red"
    elif (( T >= (45 * 60) )); then
        color="#FF8900F0" # slightly transparent orange
    elif (( T >= (30 * 60) )); then
        color="#FFFF00AF" # transparent yellow
    fi

    if [[ -n "$color" ]]; then
        printf '%s\n' "<span foreground=\"$color\">$rel_time</span>"
    else
        printf '%s\n' "$rel_time"
    fi
}

while :; do
    display
    sleep 1m
done | "$wayout_cmd" \
    --feed-line \
    --font "Noto Sans 9" \
    --height 30 \
    --width 50 \
    --text-color "#FFFFFF5E" \
    --layer overlay \
    --position bottom-left
