#!/usr/bin/env bash
# basic wayout widget timer

set -euo pipefail

# file used to store PID of running wayout widget
TIMER_FILE="/tmp/.timer-wayout"

# how often to update wayout widget
UPDATE_INTERVAL=10

# time after set timer to just quit (in seconds)
OVERTIME=600 # 10 minutes

wayout_cmd=""
if command -v wayout &>/dev/null; then
    wayout_cmd="wayout"
elif command -v proycon-wayout &>/dev/null; then # nixos
    wayout_cmd="proycon-wayout"
else
    echo "wayout not found in PATH!"
    exit 1
fi

# kill old timer if its running
if [[ -f "$TIMER_FILE" ]]; then
    echo "Killing old timer.."
    pid="$(cat "$TIMER_FILE")"
    kill -INT "-$pid" &>/dev/null || true
fi

# if no arguments just quit after killing old timer
if [[ "$#" -eq 0 ]]; then
    echo "No time specified.. quitting.."
    exit 0
fi

# write current pid into timer file
echo "$$" > "$TIMER_FILE"

# convert human time to unix timestamp using `date` command
end_time="$(date --date="$*" +'%s')"

function cleanup() {
    rm -f "$TIMER_FILE"
}
trap cleanup EXIT INT

function display() {
    passed=0
    diff="$(( end_time - $(date +'%s') ))"

    if (( diff < 0 )); then
        diff=$(( diff * -1 ))
        passed=1
    fi

    # print human readable time
    T="$diff"
    D=$((T/60/60/24))
    H=$((T/60/60%24))
    M=$((T/60%60))
    S=$((T%60))
    rel_time=""
    (( D > 0 )) && rel_time="$rel_time${D}d "
    (( H > 0 )) && rel_time="$rel_time${H}h "
    (( M > 0 )) && rel_time="$rel_time${M}m "

    if [[ -z "$rel_time" ]]; then
        rel_time="$rel_time${S}s "
    fi

    if [[ "$passed" -eq 1 ]]; then
        # turn red when time has passed
        printf '%s\n' "<span foreground=\"red\">${rel_time% }</span>"
    else
        printf '%s\n' "${rel_time% }"
    fi

    # quit timer 10 minutes after the set time
    if [[ "$passed" -eq 1 && "$diff" -gt "$OVERTIME" ]]; then
        echo "The timer has passed" >&2
        exit 0
    fi
}

# display to null so it quits before starting wayout
display &>/dev/null

while :; do
    display
    echo "<BREAK>"
    sleep "$UPDATE_INTERVAL"
done | "$wayout_cmd" \
    --feed-delimiter "<BREAK>" \
    --font "Noto Sans 9" \
    --height 30 \
    --width 50 \
    --text-color "#FFFFFF5E" \
    --layer overlay \
    --position bottom-left
