# [<file_name>]
# section = [ "Section" ]
# key = [ [ "Section", "Key" ] ]
# regex.section = [ "^Section" ]
# regex.key = [ "^Key" ]

[kwinrc]
section = [
    "$Version",
    "Xwayland",
    "Effect-colorblindnesscorrection",
]

regex.section = [ "Tiling.*" ]
regex.key = [ '^Id_\d+' ]

[dolphinrc]
section = [
    "MainWindow",
    "KPropertiesDialog",
]

key = [
    ["General", "ViewPropsTimestamp"],
    ["Open-with settings", "History"],
]

[kdeglobals]
section = [
    "DirSelect Dialog",
]

key = [
    ["General", "ColorSchemeHash"],
    ["KFileDialog Settings", "Show hidden files"],
    ["KFileDialog Settings", "Show Inline Previews"],
    ["KFileDialog Settings", "Speedbar Width"],
]

# NOTE make sure you copy the desktop files as well
# ~/.local/share/applications/net.local.*.desktop
[kglobalshortcutsrc]
section = [
    "ActivityManager",
]

# TODO removing custom keybindings as the desktop files are not saved
regex.section = [ 'services\]\[net.local.*' ]

["Trolltech.conf"]
key = [
    ["Qt", "filedialog"],
]

# GTK settings.ini
["settings.ini"]
key = [
    ["Settings", "gtk-xft-dpi"],
]

[kcminputrc]
regex.section = [
    # ignore wacom settings
    "Libinput.*Wacom"
]

[katerc]
section = [
    "MainWindow"
]

# launchers need to use 'applications:x.desktop' format
["plasma-org.kde.plasma.desktop-appletsrc"]
regex.key = [
    # on nixos its versioned so it will change every update
    "^SlidePaths$",
]

# listing other files that are important even though there is nothing to clean
[breezerc]
[kwinrulesrc]
[kscreenlockerrc]
[ksmserverrc]
[kded5rc]
[kded6rc]
[plasmashellrc]
[plasma-localerc]
[baloofilerc]
[kiorc]
[ktimezonedrc]
[kxkbrc]
[plasmarc]
[plasmaparc]
[powerdevilrc]
[powermanagementprofilesrc]
