# NOTE WIP UNTESED USE WITH CAUTION
# WARNING it clobbers! use with caution!
# It has been tested although not perfect it works pretty well

L+ %h/.config/kwinrc - - - - @dotfiles@/../kde-plasma/files/.config/kwinrc
L+ %h/.config/dolphinrc - - - - @dotfiles@/../kde-plasma/files/.config/dolphinrc
L+ %h/.config/kdeglobals - - - - @dotfiles@/../kde-plasma/files/.config/kdeglobals
L+ %h/.config/kglobalshortcutsrc - - - - @dotfiles@/../kde-plasma/files/.config/kglobalshortcutsrc
L+ %h/.config/Trolltech.conf - - - - @dotfiles@/../kde-plasma/files/.config/Trolltech.conf
L+ %h/.config/settings.ini - - - - @dotfiles@/../kde-plasma/files/.config/settings.ini
L+ %h/.config/kcminputrc - - - - @dotfiles@/../kde-plasma/files/.config/kcminputrc
L+ %h/.config/katerc - - - - @dotfiles@/../kde-plasma/files/.config/katerc
L+ %h/.config/plasma-org.kde.plasma.desktop-appletsrc - - - - @dotfiles@/../kde-plasma/files/.config/plasma-org.kde.plasma.desktop-appletsrc
L+ %h/.config/breezerc - - - - @dotfiles@/../kde-plasma/files/.config/breezerc
L+ %h/.config/kwinrulesrc - - - - @dotfiles@/../kde-plasma/files/.config/kwinrulesrc
L+ %h/.config/kscreenlockerrc - - - - @dotfiles@/../kde-plasma/files/.config/kscreenlockerrc
L+ %h/.config/ksmserverrc - - - - @dotfiles@/../kde-plasma/files/.config/ksmserverrc
L+ %h/.config/kded5rc - - - - @dotfiles@/../kde-plasma/files/.config/kded5rc
L+ %h/.config/kded6rc - - - - @dotfiles@/../kde-plasma/files/.config/kded6rc
L+ %h/.config/plasmashellrc - - - - @dotfiles@/../kde-plasma/files/.config/plasmashellrc
L+ %h/.config/plasma-localerc - - - - @dotfiles@/../kde-plasma/files/.config/plasma-localerc
L+ %h/.config/baloofilerc - - - - @dotfiles@/../kde-plasma/files/.config/baloofilerc
L+ %h/.config/kiorc - - - - @dotfiles@/../kde-plasma/files/.config/kiorc
L+ %h/.config/ktimezonedrc - - - - @dotfiles@/../kde-plasma/files/.config/ktimezonedrc
L+ %h/.config/kxkbrc - - - - @dotfiles@/../kde-plasma/files/.config/kxkbrc
L+ %h/.config/plasmarc - - - - @dotfiles@/../kde-plasma/files/.config/plasmarc
L+ %h/.config/plasmaparc - - - - @dotfiles@/../kde-plasma/files/.config/plasmaparc
L+ %h/.config/powerdevilrc - - - - @dotfiles@/../kde-plasma/files/.config/powerdevilrc
L+ %h/.config/powermanagementprofilesrc - - - - @dotfiles@/../kde-plasma/files/.config/powermanagementprofilesrc
