# NOTE WIP UNTESED USE WITH CAUTION
L$ %h/.config/kwinrc - - - - @root@/config/kde-plasma/files/.config/kwinrc
L$ %h/.config/dolphinrc - - - - @root@/config/kde-plasma/files/.config/dolphinrc
L$ %h/.config/kdeglobals - - - - @root@/config/kde-plasma/files/.config/kdeglobals
L$ %h/.config/kglobalshortcutsrc - - - - @root@/config/kde-plasma/files/.config/kglobalshortcutsrc
L$ %h/.config/Trolltech.conf - - - - @root@/config/kde-plasma/files/.config/Trolltech.conf
L$ %h/.config/settings.ini - - - - @root@/config/kde-plasma/files/.config/settings.ini
L$ %h/.config/kcminputrc - - - - @root@/config/kde-plasma/files/.config/kcminputrc
L$ %h/.config/katerc - - - - @root@/config/kde-plasma/files/.config/katerc
L$ %h/.config/plasma-org.kde.plasma.desktop-appletsrc - - - - @root@/config/kde-plasma/files/.config/plasma-org.kde.plasma.desktop-appletsrc
L$ %h/.config/breezerc - - - - @root@/config/kde-plasma/files/.config/breezerc
L$ %h/.config/kwinrulesrc - - - - @root@/config/kde-plasma/files/.config/kwinrulesrc
L$ %h/.config/kscreenlockerrc - - - - @root@/config/kde-plasma/files/.config/kscreenlockerrc
L$ %h/.config/ksmserverrc - - - - @root@/config/kde-plasma/files/.config/ksmserverrc
L$ %h/.config/kded5rc - - - - @root@/config/kde-plasma/files/.config/kded5rc
L$ %h/.config/kded6rc - - - - @root@/config/kde-plasma/files/.config/kded6rc
L$ %h/.config/plasmashellrc - - - - @root@/config/kde-plasma/files/.config/plasmashellrc
L$ %h/.config/plasma-localerc - - - - @root@/config/kde-plasma/files/.config/plasma-localerc
L$ %h/.config/baloofilerc - - - - @root@/config/kde-plasma/files/.config/baloofilerc
L$ %h/.config/kiorc - - - - @root@/config/kde-plasma/files/.config/kiorc
L$ %h/.config/ktimezonedrc - - - - @root@/config/kde-plasma/files/.config/ktimezonedrc
L$ %h/.config/kxkbrc - - - - @root@/config/kde-plasma/files/.config/kxkbrc
L$ %h/.config/plasmarc - - - - @root@/config/kde-plasma/files/.config/plasmarc
L$ %h/.config/plasmaparc - - - - @root@/config/kde-plasma/files/.config/plasmaparc
L$ %h/.config/powerdevilrc - - - - @root@/config/kde-plasma/files/.config/powerdevilrc
L$ %h/.config/powermanagementprofilesrc - - - - @root@/config/kde-plasma/files/.config/powermanagementprofilesrc
