# contains common configuration options

# use solid color by default
output * bg #181A27 solid_color

# i do not like it
primary_selection disabled

# TODO should this be enabled?
seat * hide_cursor 8000

# remove title but leave border on focused window
default_border pixel
default_floating_border normal

# only show borders between windows
hide_edge_borders both

# do not follow mouse
focus_follows_mouse no

# vim: ft=swayconfig
