# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fa64d2ec-005e-4a2a-a9e2-4fc1cec05ec7";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9471-17E8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # mount slow hdd
  fileSystems."/mnt/slowmf" =
    { device = "/dev/disk/by-uuid/5046099b-f7f8-4fab-9e76-d295687bb2a8";
      fsType = "ext4";
      options = [
        "defaults"
        "noatime"
        "nodiratime"
        "nofail"
      ];
    };

  # TODO add username variable do not hardcode it
  # NOTE: links are fragile, any kind of containerization breaks them so bind mounts instead
  fileSystems."/home/sandorex/slowmf" =
    { device = "/mnt/slowmf";
      depends = [
        "/mnt/slowmf"
      ];
      fsType = "none";
      options = [
        "bind"
        "nofail"
      ];
    };

  fileSystems."/home/sandorex/ws" =
    { device = "/mnt/slowmf/ws";
      depends = [
        "/mnt/slowmf"
      ];
      fsType = "none";
      options = [
        "bind"
        "nofail"
      ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
