-- loads all config modules
require("config.options")
require("config.treesitter")
require("config.lsp")
require("config.netrw")
require("config.statusline")
require("config.statuscolumn")
require("config.diagnostics")
require("config.keybindings")
require("config.tabline")
require("config.context_menu")
require("config.highlight")
