# input devices

input type:keyboard {
    xkb_layout us
    xkb_options caps:super

    repeat_delay 400
    repeat_rate 25
}

input "1241:64514:USB_Laser_Game_Mouse" {
    accel_profile "flat"
    pointer_accel "0.05"
}

input "1133:16418:Logitech_Wireless_Mouse_PID:4022" {
    accel_profile "flat"
    pointer_accel "-0.2"
}

input "1241:41119:E-Signal_USB_Gaming_Mouse" {
    accel_profile "flat"
    pointer_accel "0.0"
}
