font_family      family="UbuntuMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto

# the font is smaller for some reason? 18 is same size as 16 for firacode?
font_size 18
